project:
  type: website

website:
  title: Dagmar Heintze
  navbar:
    right:
      - href: index.hml
        text: Home
      - text: Research
        menu: 
        - href: research.html
          text: Peer-reviewed Research
        - href: workingpapers.html
          text: Working Papers
      - text: Conference Presentations
        menu: 
        - href: 2023APSA_presentation_DHeintze.pdf
          text: APSA 2023
        - href: 2024MPSA_presentation_DHeintze.pdf
          text: MPSA 2024
      - href: CV_2025.pdf
        text: CV 
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

