---
title: "Working Papers"
---

---
format: 
  html:
    theme: sandstone
    include:
      in_header: "style.css"
---

::: workingpapers-text
My current working papers and works in progress include:

-   **“Unpacking the Gendered Dimensions of Political Violence: Coparticipation and Centrality of Women in the Rwandan Genocide” with Jared F. Edgerton, Elizabeth L. Brannon, & Hollie Nyseth Nzitatira**

    Abstract:

    How does gender impact genocidal violence? Previous research on genocide has explored the gendered dimensions of political violence, with scholars emphasizing that although women engage in and perpetrate genocidal violence, they are less likely to do so than men. In the Rwandan genocide, women’s participation was significantly more common than in other genocidal contexts, but scholars and practitioners have still ascertained that the majority of women participated differently than men due to the patriarchal norms, taking on primarily less violent looting roles while men primarily committed murders. Drawing on gendered understandings of genocide, armed conflict, and non-state armed groups, we focus on the individual decision of genocide participants to engage in violent acts and argue that an individual’s mobilization to participate in the violence is contingent on their own gender, as well as the gender of their mobilizer. In particular, we expect that women will play a key role in socializing other women toward violence. To test this argument, we leverage novel data on the 1994 Genocide in Rwanda. Using network analysis, we demonstrate women’s vital role in mobilizing other women to commit violence in Rwanda. This article builds on insights into the social network dynamics of various conflict settings and highlights the pertinence of disentangling gendered differences in network relationships.

-   **“Domestic Human Rights NGOs and Victim's Support in International Human Rights Litigation”**

    Abstract:

    How do victims of government human rights abuse gain access to international human rights litigation? Domestic Human Rights NGOs in autocratic regimes take on a variety of roles, including educating victims of political violence on the existence of human rights and their violation, connecting victims to networks of domestic and international Human Rights NGOs, and assisting victims in their attempt to lodge complaints with the domestic court system in their attempt to seek compensation for the violations they suffered. Despite previous research highlighting the crucial role Human Rights NGOs play in supporting victims of political violence in autocratic regimes, there is a dearth of research on whether domestic Human Rights NGOs support victims when attempting to file individual communications with the UN Treaty Bodies after having exhausted domestic remedies. Do domestic Human Rights NGOs educate victims of political violence in autocratic regimes on filing individual communications after large-scale political violence, and does the number of domestic Human Rights NGOs influence the number of victims who file individual communications and gain access to international litigation? This project begins to answer this question by exploring the relationship between the number of domestic Human Rights NGOs and the number of individual communications after incidents of large-scale violence in autocratic regimes, utilizing an original dataset of international non-governmental organization data and the number of individual communications to the UN treaty bodies. This project advances our understanding of the role domestic Human Rights NGOs play in supporting victims of political violence in international human rights litigation.

:::
